// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRaJhmWcVPUPP7nEaFUCCv75V0NeZl8Nk',
    appId: '1:928278600395:web:3110d1704bc8a0f3a8594e',
    messagingSenderId: '928278600395',
    projectId: 'clone-aom',
    authDomain: 'clone-aom.firebaseapp.com',
    storageBucket: 'clone-aom.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIhmvMXiZPzfIihVG6VqPYNeQV6rCkV3g',
    appId: '1:928278600395:android:1fe61f78dd69cd28a8594e',
    messagingSenderId: '928278600395',
    projectId: 'clone-aom',
    storageBucket: 'clone-aom.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA66kfhkmTzfmsmrHqKUB-MccNsKC3lHxE',
    appId: '1:928278600395:ios:8d6d8768e3d031a6a8594e',
    messagingSenderId: '928278600395',
    projectId: 'clone-aom',
    storageBucket: 'clone-aom.firebasestorage.app',
    iosBundleId: 'com.example.cloneAom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA66kfhkmTzfmsmrHqKUB-MccNsKC3lHxE',
    appId: '1:928278600395:ios:8d6d8768e3d031a6a8594e',
    messagingSenderId: '928278600395',
    projectId: 'clone-aom',
    storageBucket: 'clone-aom.firebasestorage.app',
    iosBundleId: 'com.example.cloneAom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRaJhmWcVPUPP7nEaFUCCv75V0NeZl8Nk',
    appId: '1:928278600395:web:e431243eccf5f985a8594e',
    messagingSenderId: '928278600395',
    projectId: 'clone-aom',
    authDomain: 'clone-aom.firebaseapp.com',
    storageBucket: 'clone-aom.firebasestorage.app',
  );
}
